server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysqlserver:3306/testdb
    username: myuser
    password: mypassword
    tomcat:
      test-while-idle: true
      validation-query: select 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

